apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "flipper"
  annotations:
    github.com/project-slug: magusd/flipper
spec:
  type: service
  owner: user:magusd
  lifecycle: experimental
